In [2]:
import pandas as pd
import numpy as np

In [3]:
from sklearn import datasets
digits = datasets.load_digits()

In [18]:
from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100.)

In [19]:
clf

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [20]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [21]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [22]:
clf.fit(digits.data[:-1], digits.target[:-1])

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [23]:
clf.predict(digits.data[-1:])

array([8])

In [25]:
digits.images[8]

array([[ 0.,  0.,  9., 14.,  8.,  1.,  0.,  0.],
       [ 0.,  0., 12., 14., 14., 12.,  0.,  0.],
       [ 0.,  0.,  9., 10.,  0., 15.,  4.,  0.],
       [ 0.,  0.,  3., 16., 12., 14.,  2.,  0.],
       [ 0.,  0.,  4., 16., 16.,  2.,  0.,  0.],
       [ 0.,  3., 16.,  8., 10., 13.,  2.,  0.],
       [ 0.,  1., 15.,  1.,  3., 16.,  8.,  0.],
       [ 0.,  0., 11., 16., 15., 11.,  1.,  0.]])

In [34]:
#grava o modelo (modelo persistente) em uma variável
import pickle
s = pickle.dumps(clf)

#carrega o modelo salvo na variável s2
s2 = pickle.loads(s)

In [30]:
#grava o modelo (modelo persistente) em um arquivo
from joblib import dump, load
dump(clf, 'modelo_clf.joblib') 

['modelo_clf.joblib']

In [32]:
#carrega o modelo salvo na variável clf2
clf2 = load('modelo_clf.joblib')

In [33]:
type(clf2)

sklearn.svm.classes.SVC

In [35]:
type(s)

bytes

In [36]:
type(s2)

sklearn.svm.classes.SVC